### ISSUE TITLE
mpy-cross reports invalid syntax in wifi.py, line 26

### ISSUE THREAD

**Issue by DonvdH** [jeffmer/TTGO-T-watch-2020-Micropython-OS#12]
mpy-cross reports a syntax error in wifi.py, line 26:

    mpy-cross -march=xtensawin ./wifi.py
    Traceback (most recent call last):
    File "./wifi.py", line 26
    SyntaxError: invalid syntax

wifi.py contains an 'else' statement following an 'else' statement.

Looking at the code, lines 26 and 27 need to be removed.

**Comment by thiswillbeyourgithub** [comment]
I am the culprit i think. I noticed that mistake in my personnal fork and forgot to update here. I'm sorry!

**Comment by DonvdH** [comment]
No problem at all, thanks for your efforts and the quick resolution! :)
