### ISSUE TITLE
Screen refreshes every 20 seconds

### ISSUE THREAD

**Issue by scott8** [jeffmer/TTGO-T-watch-2020-Micropython-OS#21]
The screen goes blank and refreshes every 20 seconds. I suspect it is supposed to be going dark to conserve power?

**Comment by jeffmer** [comment]
That happens sometimes if the alarm interrupt is not cleared. Try setting and clearing an alarm.

**Comment by scott8** [comment]
That works. Thanks. Now it goes to sleep like it should also.
