### ISSUE TITLE
How do you set rtc

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [jeffmer/TTGO-T-watch-2020-Micropython-OS#8]
Hi,

On my setup running `mpremote a0 setrtc` seems to only make the watch instantly reboot so I'm looking for straightforward ways to set the actual time automatically after a flash.

Do you have any scripts to share?

Thanks

**Comment by jeffmer** [comment]
I use the “Sync with NTP” function provided by the Timeman utility. This uses Wifi so that has to be setup. However, this is not automatic - you need to press the button.

**Comment by thiswillbeyourgithub** [comment]
Oh okay thanks.
